bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root to: 'books#top'
  resources :users
  get 'about' => 'books#about'
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true, length:{maximum:200}
	validates :body, presence: true, length:{maximum:200}
    belongs_to :user
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image

  has_many :books, dependent: :destroy

  validates :introduction, length: { maximum: 20 }

  validates :name, presence: true, uniqueness: true, length: {maximum: 20, minimum: 2 }

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    books_path # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end
  # def new
		# @book = Book.newprotected

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
  # end
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
	def top
	end
	def index
		@book = Book.new
		@books = Book.all
	end
	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		@books = Book.all
		if @book.save
        flash[:notice] = "successfully"
        redirect_to book_path(@book.id)
        else
        	render :index
        end
	end
	def show
		@book_find = Book.find(params[:id])
		@book = Book.new
		@books = Book.all
	end
	def edit
        @book_edit = Book.find(params[:id])
        @book = Book.new
    end
    def update
    	book = Book.find(params[:id])
        book.update(book_params)
        if book.update(book_params)
        flash[:notice] = "successfully"
        redirect_to book_path(book.id)
    end
    end
    def destroy
    	book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
    end
    def about

    end

	private

    def book_params
      params.require(:book).permit(:title, :body)
    end
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
  end
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @books = Book.all
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end
  def show
  	@user = User.find(params[:id])
    @user.books
    @book = Book.new
    @book.user_id = current_user.id
  end
  def edit
  	 @user_edit = User.find(params[:id])
  end
  def update
      user = User.find(current_user.id)
      if user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to books_path(user.id)
  end
  end
  private

    def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
    end
end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/root_helper.rb
module RootHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/books/about.html.erb
<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!!</h1>

bookers2/app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for @book_edit, url: book_path do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
<% end %>
<div>
	<p><%= link_to 'show',book_path %>|<%= link_to 'back', books_path %></p>
</div>

bookers2/app/views/books/header.html.erb
<% content_for :header do %>
	
<% end %>

bookers2/app/views/books/index.html.erb
<style type="text/css" media="screen">
</style>
<section class="mine">
     <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
	<h1>User info</h1>
    <%= attachment_image_tag current_user, :profile_image, size:'150x150', fallback: "def.jpeg"  %>
    <table>
        <tr>
                <th>name</th><td><%= current_user.name %></td>
        </tr>
        <tr>
                <th>data</th><td><%= current_user.introduction %></td>
        </tr>
    </table>
    <%= link_to edit_user_path(current_user.id) do %>
　<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
<% end %>
</section>
<section class="create">
<h1>New Book</h1>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>件のエラーがあります。</h2>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<!-- form_for部分 -->
<%= form_for @book, url: books_path do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>

<% end %>
</section>

<section class="detail">
 <h1>Books</h1>
 <table class="table">
 	<tr>
 		<th></th>
 		<th>Title</th>
 		<th>Opinion</th>
 	</tr>
 <% @books.each do |book| %>
    <tr>
    	<th><%= attachment_image_tag book.user, :profile_image, size:'50x50', fallback: "def.jpeg"  %></th>
    	<th><%=link_to book.title, "/books/#{book.id}" %></th>
    	<th><%= book.body %></th>
    </tr>
 <% end %>
</table>
</section>

bookers2/app/views/books/show.html.erb
<style type="text/css" media="screen">
</style>
<section class="mine">
     <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <h1>User info</h1>
    <%= attachment_image_tag current_user, :profile_image, size:'150x150', fallback: "def.jpeg"  %>
    <table>
        <tr>
                <th>name</th><td><%= current_user.name %></td>
        </tr>
        <tr>
                <th>data</th><td><%= current_user.introduction %></td>
        </tr>
    </table>
    <%= link_to edit_user_path(current_user.id) do %>
　<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
<% end %>
</section>
<section class="create">
<h1>New Book</h1>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>件のエラーがあります。</h2>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<!-- form_for部分 -->
<%= form_for @book, url: books_path do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>

<% end %>
</section>

<section class="detail">
 <h1>Book detail</h1>
 <table class="table">
    <tr>
        <th><%= attachment_image_tag current_user, :profile_image, size:'50x50', fallback: "def.jpeg"  %></th>
        <th><%= @book_find.title %></th>
        <th><%= @book_find.body %></th>
        <th><%= link_to "edit", edit_book_path , class: 'btn btn-default' %></th>
        <th><%= link_to "destroy", book_path(@book_find.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: 'btn btn-default' %>
 </th>
    </tr>
</table>
</section>

bookers2/app/views/books/top.html.erb
<!DOCTYPE html>
<html>
<head>
	<style type="text/css">
		.container{
			margin: 0 115px;
			padding: 0 15px;
		}
		.btn{
			margin-bottom: 0;
		}
		.btn-login{
			background-color: blue;
		}
		.btn-signup{
			background-color: green;
		}
		button{
			color: white;
		}
	</style>
</head>
<body>
	<div class="container">
	<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!!</h1>
	<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><b>Bookers,</b><br>you can share and exchange your opinions , inpressions , and emotions<br>about varioius books!</p>
	<button type="button" class="btn btn-login btn-block"><%=link_to "Log in" , user_session_path %></button>
	<button type="button" class="btn btn-signup btn-block"><%= link_to "Sign up" , new_user_registration_path %></button>
    </div>
</body>
</html>

bookers2/app/views/layouts/_error_mesages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="slidemenu">
  <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
    <% if user_signed_in? %>
      <li class="">
        <span class="glyphicon glyphicon-log-in" aria-hidden="true"><%= link_to "  logout", destroy_user_session_path, method: :delete %></span>
      </li>
    <!--   <li class="">
      </li> -->
      <li class="">
        <!-- ↓以下のコードは、5章で正しいroutingに書き直します。 -->
        <span class="glyphicon glyphicon-user" aria-hidden="true"><%= link_to '  Users', users_path %></span>
      </li>
      <li>
        <span class="glyphicon glyphicon-home" aria-hidden="true"><%= link_to '  Home', user_path(current_user.id) %></span>
      </li>
      <li>
        <span class="glyphicon glyphicon-book" aria-hidden="true"><%= link_to '  Books', books_path %></span>
      </li>
    <% else %>
      <li class="">
        <span class="glyphicon glyphicon-download-alt" aria-hidden="true"><%= link_to "  sign up", new_user_registration_path %></span>
      </li>
      <li class="">
        <span class="glyphicon glyphicon-log-in" aria-hidden="true"><%= link_to "  login", new_user_session_path %></span>
      </li>
      <li>
        <span class="glyphicon glyphicon-home" aria-hidden="true"><%= link_to '  Home', root_path %></span>
      </li>
      <li>
        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"><%= link_to '  About', about_path %></span>
      </li>
    <% end %>
  </ul>
</div>
    <!-- <div class="header">
      <header>
    <div class="container">
      <nav>
        <span>Bookers</span>
      </nav>
      <nav>
        <ul>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
        </ul>
      </nav>
    </div>
  </header>
    </div> -->
    <%= yield %>
  </body>
</html>

bookers2/app/views/users/edit.html.erb
<h1>User info</h1>
          <%= form_for @user_edit, url:  user_path do |f| %>

    	　　<p><b>Name</b></p>
            <%= f.text_field :name %>

            <p><b>Image</b></p>
            <%= f.attachment_field :profile_image %>

            <p><b>Introduction</b></p>
            <%= f.text_area :introduction %>

            <%= f.submit 'Update User' %>

          <% end %>

bookers2/app/views/users/index.html.erb
<style type="text/css" media="screen">
</style>
<section class="mine">
     <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
	<h1>User info</h1>
    <%= attachment_image_tag current_user, :profile_image, size:'150x150', fallback: "def.jpeg"  %>
    <table>
        <tr>
                <th>name</th><td><%= current_user.name %></td>
        </tr>
        <tr>
                <th>data</th><td><%= current_user.introduction %></td>
        </tr>
    </table>
    <%= link_to edit_user_path(current_user.id) do %>
　<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
<% end %>
</section>
<section class="create">
<h1>New Book</h1>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>件のエラーがあります。</h2>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<!-- form_for部分 -->
<%= form_for @book, url: books_path do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>

<% end %>
</section>

<section class="detail">
 <h1>Users</h1>
 <table class="table">
 	<tr>
 		<th>image</th>
 		<th>name</th>
 		<th></th>
 	</tr>
 <% @users.each do |user| %>
    <tr>
    	<th><%= attachment_image_tag user, :profile_image, size:'50x50', fallback: "def.jpeg"  %></th>
    	<th><%= user.name %></th>
    	<th><%= link_to 'show', user_path(user.id) %></th>
    </tr>
 <% end %>
</table>
</section>

bookers2/app/views/users/show.html.erb
<style type="text/css" media="screen">
</style>
<section class="mine">
     <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
	<h1>User info</h1>
    <%= attachment_image_tag current_user, :profile_image, size:'150x150', fallback: "def.jpeg" %>
    <table>
        <tr>
                <th>name</th><td><%= current_user.name %></td>
        </tr>
        <tr>
                <th>data</th><td><%= current_user.introduction %></td>
        </tr>
    </table>
    <%= link_to edit_user_path(current_user.id) do %>
　<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
<% end %>
</section>
<section class="create">
<h1>New Book</h1>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>件のエラーがあります。</h2>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<!-- form_for部分 -->
<%= form_for @book, url: books_path do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>

<% end %>
</section>

<section class="detail">
 <h1>Books</h1>
 <table class="table">
 	<tr>
 		<th></th>
 		<th>Title</th>
 		<th>Opinion</th>
 	</tr>
 <% @user.books.each do |book| %>
    <tr>
    	<th><%= attachment_image_tag book.user, :profile_image, size:'50x50', fallback: "def.jpeg"  %></th>
    	<th><%=link_to book.title, "/books/#{book.id}" %></th>
    	<th><%= book.body %></th>
    </tr>
 <% end %>
</table>
</section>