bookers/config/routes.rb
Rails.application.routes.draw do
  root :to => 'books#top'
  get 'index' =>'books#index'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id'=> 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  get 'books/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources
end

bookers/app/models/book.rb
class Book < ApplicationRecord
end

bookers/app/models/post.rb
class Post < ApplicationRecord
end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
	@newbook = Book.new
	@books = Book.all
  end

  def create
  	newbook = Book.new(book_params)
  	# newbook.save
  	# redirect_to book_path(newbook.id)
  	if newbook.save
      flash[:notice] = "successfully"
      redirect_to book_path(newbook.id)
    end
  end

  def show
  	@book = Book.find(params[:id])
  end

  def update
  	newbook = Book.find(params[:id])
    # newbook.update(book_params)
    # redirect_to book_path(newbook.id)
    if newbook.update(book_params)
    flash[:notice] = "successfully"
    redirect_to book_path(newbook.id)
    end
  end

  def edit
  	@newbook = Book.find(params[:id])
  end

  def destroy
     newbook = Book.find(params[:id])
     newbook.destroy
     redirect_to books_path
  end

  private

  def book_params
  	params.require(:book).permit(:title,:body)
  end
end

bookers/app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@newbook) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
<% end %>
<p><%=link_to "edit", edit_book_path(@newbook.id), class: "edit_#{@newbook.id}"  %>
   |
   <%=link_to "back", "/edit", class: "back" %>
</p>

bookers/app/views/books/index.html.erb
 <style type="text/css">
 </style>
 <h1>Books</h1>
 <table width="80%">
    <tr>
    	<th width="25%">Title</th>
    	<th width="50%">Body</th>
    </tr>

 <% @books.each do |book| %>
    <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%=link_to "show", book_path(book.id), class: "show_#{book.id}" %></td>
    <td><%=link_to "edit", edit_book_path(book.id), class: "edit_#{book.id}"  %></td>
    <td><%=link_to 'destroy', destroy_book_path(book.id), method: :'delete',"data-confirm" => "Are you sure?" , class: "destroy_#{book.id}" %></td>
    </tr>
 <% end %>
</table>

<h2>New book</h2>

<%= form_for(@newbook) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title,class:"book_title" %>

    <h4>Body</h4>
    <%= f.text_area :body,class:"book_body" %><br>
    <%= f.submit 'Create Book' %>

<% end %>

bookers/app/views/books/show.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
<h2>Title</h2>
<p><%= @book.title %></p>
<h2>Body</h2>
<p><%= @book.body %></p>
<p><%=link_to "edit", edit_book_path(@book.id), class: "edit#{@book.id}" %>
   |
   <%=link_to "back", books_path(@book.id), class: "back" %>
</p>

bookers/app/views/books/top.html.erb
<h1>ようこそBookersへ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や<br>
印象を共有し交換することができます
</p>
<%= link_to 'start','/index' %>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>